apiVersion: v1
kind: ReplicationController
metadata:
  name: es-client
  labels:
    component: elasticsearch
    role: client
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: client
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es-client
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: docker.io/wleferrand/experiments
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: HTTP_CORS_ENABLED
          value: "true"
        - name: HTTP_CORS_ALLOW_ORIGIN
          value: "*"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
